### ISSUE TITLE
Ubuntu Support?

### ISSUE THREAD

**Issue by roadglide03** [UCTRONICS/U6143_ssd1306#1]
I have Ubuntu Server running for Raspberry 4 pi and wanted to use the LCD display from your product.  I  was wondering if there is a way to get this running without going to Raspberry OS.  I plan on using it in my home lab for Kubernetes and other.  thanks

**Comment by dison4linux** [comment]
You'll have to manually download and install raspi-config from somewhere like
[https://archive.raspberrypi.org/debian/pool/main/r/raspi-config/raspi-config_20210212_all.deb](url)
to get I2C enabled (or manually enable it).
And also you'll have to install the fonts-dejavu packages (as the Ubuntu server images don't usually include fonts)
but after that, python is python, just follow the instructions as if you were running it on Raspbian

**Comment by roadglide03** [comment]
got it fixed thanks
