### ISSUE TITLE
Compatibility with dietpi?

### ISSUE THREAD

**Issue by NotCoolKiwi** [UCTRONICS/U6143_ssd1306#13]
is there any way I can use this on the operating system dietpi? I have turned I2C on and it gives me this error:

```
rm -rf *.o
rm -rf display
cc    -c -o display.o display.c
cc    -c -o ssd1306_i2c.o ssd1306_i2c.c
ssd1306_i2c.c:7:10: fatal error: wiringPiI2C.h: No such file or directory
 #include <wiringPiI2C.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: ssd1306_i2c.o] Error 1
```

**Comment by eshicks4** [comment]
You just need to "apt install wiringpi".  That part isn't mentioned in the instructions yet. (probably should be)

**Comment by NotCoolKiwi** [comment]
E: Unable to locate package wiringpi

**Comment by NotCoolKiwi** [comment]
I was able to install it with dietpi-software. it works now!
