### ISSUE TITLE
How is the BMP.h chars coded?

### ISSUE THREAD

**Issue by robiwisc** [UCTRONICS/U6143_ssd1306#7]
Does anyone know how the unsigned chars in the BMP.h file are coded/have a table of values? I'm trying to add additional arrays for different views.

**Comment by alpayne** [comment]
The file contains three 512-byte pixel arrays for the three possible bitmaps. Each byte is 8 vertical pixels, and the addressing is horizontal, so it'll move along across the display before shifting down to the next 128x8 page.

The first array produces this image:

![bitmap1](https://user-images.githubusercontent.com/1106057/114811802-c580f300-9d7c-11eb-8155-bc48d3bf5e58.png)

**Comment by WaaromZoMoeilijk** [comment]
Thanks for the info, is there any additional documentation available on this elsewhere? I'm trying to adjust Fahrenheit to celcius and also want to add some more pages.
