### ISSUE TITLE
Ubuntu install - fatal error: wiringPiI2C.h: No such file or directory

### ISSUE THREAD

**Issue by scockman** [UCTRONICS/U6143_ssd1306#8]
After getting raspi-config installed and I2C interface enabled and verify. I was following the instructions and during the make process I received the following:

`ssd1306_i2c.c:7:10: fatal error: wiringPiI2C.h: No such file or directory
    7 | #include <wiringPiI2C.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: ssd1306_i2c.o] Error 1`

Should wiringPiI2C.h be part of the code or do I need to add to the directory?

**Comment by alpayne** [comment]
You'll need to install _libwiringpi-dev_ on Ubuntu to get the library you're missing.

**Comment by lamberts69** [comment]
This command resolve the compilation error on my side sudo apt-get install wiringpi

**Comment by scockman** [comment]
@alpayne running the command "sudo apt-get install libwiringpi-dev" did the trick.

@lamberts69 I did try that, but somehow it did not work. But running the one @alpayne suggested did. I am now up and running.

Closing the issue.
